/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_meshpoint_anode_RuntimeNative */

#ifndef _Included_org_meshpoint_anode_RuntimeNative
#define _Included_org_meshpoint_anode_RuntimeNative
#ifdef __cplusplus
extern "C" {
#endif
#undef org_meshpoint_anode_RuntimeNative_SIGINT
#define org_meshpoint_anode_RuntimeNative_SIGINT 2L
#undef org_meshpoint_anode_RuntimeNative_SIGKILL
#define org_meshpoint_anode_RuntimeNative_SIGKILL 9L
#undef org_meshpoint_anode_RuntimeNative_SIGTERM
#define org_meshpoint_anode_RuntimeNative_SIGTERM 15L
/*
 * Class:     org_meshpoint_anode_RuntimeNative
 * Method:    start
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_meshpoint_anode_RuntimeNative_start
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_meshpoint_anode_RuntimeNative
 * Method:    stop
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_meshpoint_anode_RuntimeNative_stop
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
